name: Detect markdown file changes and trigger build action

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    outputs:
      mutation: ${{ steps.check_md_files.outputs.result }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Check for changed markdown files
        id: check_md_files
        run: |
          echo "Checking for changes in the latest push."
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            git diff --name-only HEAD^ HEAD | grep '\.md$' || echo "no-md-files" >> "$GITHUB_OUTPUT"
          else
            echo "First commit detected, checking only HEAD."
            git diff --name-only HEAD | grep '\.md$' || echo "no-md-files" >> "$GITHUB_OUTPUT"
          fi

      - name: test
        run: echo ${{ steps.check_md_files.outputs.result }}

      - name: Trigger build action if markdown are changed
        if: steps.check_md_files.outputs.result != 'no-md-files'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/30fyllos/multi-repo-md/dispatches \
          -d '{"event_type": "trigger-build"}'
          echo "Event dispatched successfully."
