name: Detect markdown file changes and trigger build action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Check for changed markdown files
        id: check_md_files
        run: |
         if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "Checking for changes between base and head of pull request."
            git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.md$' || echo "no-md-files"
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "Checking for changes in the latest push."
            git diff --name-only HEAD^ HEAD | grep '\.md$' || echo "no-md-files"
          fi

      - name: Trigger build action if markdown are changed
        if: steps.check_md_files.outputs.files != 'no-md-files'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/30fyllos/multi-repo-md/dispatches \
          -d '{"event_type": "trigger-build"}'
          echo "Event dispatched successfully."
