name: Detect markdown file changes and trigger build action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true || github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Check for changed markdown files
        id: check_md_files
        run: |
          md_changed="false"
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" ]]; then
           echo "Checking for changes between base and head of pull request."
           if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep '\.md$'; then
             md_changed="true"
           fi
          elif [[ "${{ github.event_name }}" == "push" ]]; then
           echo "Checking for changes in the latest push."
           if git rev-parse HEAD^ >/dev/null 2>&1; then
             if git diff --name-only HEAD^ HEAD | grep '\.md$'; then
               md_changed="true"
             fi
           else
             echo "First commit detected, checking only HEAD."
             if git diff --name-only HEAD | grep '\.md$'; then
               md_changed="true"
             fi
           fi
          fi
          echo "Markdown files changed: $md_changed"
          echo "::set-env name=MD_CHANGED::$md_changed"

      - name: Trigger build action if markdown are changed
        if: env.MD_CHANGED == 'true'
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/30fyllos/multi-repo-md/dispatches \
          -d '{"event_type": "trigger-build"}'
          echo "Event dispatched successfully."
